### PR TITLE
Issue #201 Porting ml_convertRotationOrder.py to mmSolver

### PR DESCRIPTION
**Pull request by ktonegawa**
Creating Pull Request to start progress of Issue https://github.com/david-cattermole/mayaMatchMoveSolver/issues/201

For now I just simply added the script files and just added them to the General Tools menu.

I would like to clarify

1) Should the `ml_utilities.py` go into an actual `utils` directory and `ml_convertRotationOrder.py` into `tools` directory to keep the formatting consistent?
2) Could you clarify what you mean by:
> Alternatively, the "check rotation order" feature is really helpful, however sometimes a user may want to change the rotation order for many objects at once (something the UI does not allow). 

From what I can see [from this line here](https://github.com/ktonegawa/mayaMatchMoveSolver/commit/a445d01d39d61d7fc1f367757e1d703221f46bed#diff-db23d3d86af706ae77d70dcbc56dba87646a60cd764e1cd3d6fe4d7b35086424R284) seems like the tool already does iterate through the list of selections to change the rotation order. Are you referring to setting different rotation orders for multiple objects? If so perhaps we could put together a new UI...?

3) Do the copyright/licensing texts seem okay as is...?

### CODE REVIEW

**Comment by david-cattermole** [comment]
Hi @ktonegawa,

This looks really good!

> Should the ml_utilities.py go into an actual utils directory and ml_convertRotationOrder.py into tools directory to keep the formatting consistent?

I think the location (`./python/mmSolver/tools/mltools/`) you've picked is perfect.
This keeps all the tools in the same location.
In the future if we add more we can place them in the same directory.
We do not need to put the `ml_utilities.py` into the `./python/mmSolver/utils`.

> Could you clarify what you mean by:
>> Alternatively, the "check rotation order" feature is really helpful, however sometimes a user may want to change the rotation order for many objects at once (something the UI does not allow).

It was in relation to a tool to check how "gimbal flipped" all the selected transform nodes are.

For example if you follow these steps you will get a warning "Please select a single object".

1) Open "ml Convert Rotation Order" UI.
2) Select 2 or more transform nodes.
3) Press "Get tips for selection".
A warning will be printed.

If only 1 transform node is selected then the UI updates and lists the gimbal flipping amount.
I will add another issue about such a tool. the ml tools do not have a tool to list this information without the UI.

Example UI and selection:
image

`# Warning: Please select a single object.`:
image

**Comment by david-cattermole** [comment]
@ktonegawa the only issue I can see in your PR, can you add the new tool UI into the `config/menu.json` and `config/shelf_minimal.json` files as well?

https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/config/menu.json
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/config/shelf_minimal.json

Otherwise I'm happy to merge this PR and include in the v0.3.15 release.

**Comment by david-cattermole** [comment]
@ktonegawa I have written up the "check rotation order" tool description in more detail here:
https://github.com/david-cattermole/mayaMatchMoveSolver/issues/234

**Comment by ktonegawa** [comment]
Hi @david-cattermole I added this tool under those json files you mentioned and I also slapped something together and put up Pull Request https://github.com/david-cattermole/mayaMatchMoveSolver/pull/235 to get something going...

**Comment by david-cattermole** [comment]
This looks good to me. I will merge this PR in the next 8 hours.

There are a few things I'll need to check and possibly add:
- another license file for the ML tools MIT license - this will also be installed.
-  double check adding your name into the headers of files and the new 2022 copyright year.
When it's merged I'll close the PR and update the issue.

This should be released in v0.3.15.

**Review by david-cattermole — APPROVED** [review]
This looks good! Thanks @ktonegawa!

**Comment by ktonegawa** [comment]
glad to hear that, thank you @david-cattermole !

**Pull request merged**
